### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Herojhjh** [NL-4-DEVS/Eggwars#56]
[11:24:57] [Server thread/CRITICAL]: ErrorException: "Undefined index:" (EXCEPTION) in "plugins/Eggwars.phar/src/Driesboy/EggWars/EggWars" at line 383
[11:24:58] [Server thread/CRITICAL]: Could not execute task Driesboy\EggWars\Task\Game: Undefined index:

**Comment by SuperKali** [comment]
The version you use?

**Comment by Herojhjh** [comment]
newest from poggit

**Comment by Herojhjh** [comment]
https://github.com/NL-4-DEVS/Eggwars/blob/master/src/Driesboy/EggWars/EggWars.php#L383

**Comment by Herojhjh** [comment]
when the game start i cant move and spamming console

**Comment by SuperKali** [comment]
Pmmp and Genisys?

**Comment by Herojhjh** [comment]
pmmp

**Comment by SuperKali** [comment]
On my server work ip play.networkgames.eu

**Comment by Herojhjh** [comment]
last week i try this lugin work with 2 player

**Comment by Herojhjh** [comment]
and when i join the game with 4 team only give me 3wools

**Comment by SuperKali** [comment]
The one that delivers 3 wires instead of 4 and a visual bug

On Jul 5, 2017 2:14 PM, "Herojhjh" <notifications@github.com> wrote:

and when i join the game with 4 team only give me 3wools

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/NL-4-DEVS/Eggwars/issues/56#issuecomment-313085370>,
or mute
the thread

**Comment by Herojhjh** [comment]
so why this plugin  not work for me but its work for you

**Comment by bounait** [comment]
How i can spawn drangon egg in poketmine pmmp ????

**Comment by Herojhjh** [comment]
just add dragon egg code on pocketmine/block

**Comment by Driesboy** [comment]
plz setup agian
